name: Automation Workflow
on:
  push:
    branches:
      - feature/**
  pull_request:
    branches: 
        - develop
jobs:
  BUILD:
    runs-on: ubuntu-20.04
    steps:
      - name: clone repo
        uses: actions/checkout@v2.3.5
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.branch }}
          fetch-depth: 1
      - name: lint commits
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: "./commitlint.config.js"
          firstParent: true
          failOnWarnings: true
      - name: setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'npm'
      - name: install npm dependencies
        run: npm install
      - name: lint git branch
        run: npx branch-name-lint options.json
      - name: lint source code
        run: npm run lint
      - name: lint docker code
        run: npx dockerfilelint Dockerfile
      - name: check app build
        run: npm run build-prod
       
        