# name: Deployment Workflow
# on:
#   push:
#     branches:
#       - release/**
# jobs:
#   DEPLOY:
#     name: DEPLOY
#     runs-on: ubuntu-20.04
#     if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
#     steps:
#       - name: Login Container Registry
#         run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin<<<'${{ secrets.DOCKERHUB_TOKEN }}'
#         shell: bash
#       - name: clone repo
#         uses: actions/checkout@v2.3.5
#         with:
#           repository: ${{ env.CUST_REPOSITORY_ENV }}
#           ref: ${{ env.CUST_BRANCH_ENV }}
#           fetch-depth: 1
#       - name: Build Container Image
#         run: docker build -t andromeda:latest . --compress
#         shell: bash
#       - name: Tag Container Image
#         run: docker tag andromeda:latest dockerdemopai/andromeda:v0.0.1
#         shell: bash
#       - name: Push to Container Registry
#         run: docker push dockerdemopai/andromeda:v0.0.1
#         shell: bash