name: Deployment Workflow
on:
  push:
    branches:
      - feature/**
jobs:
  RELEASE:
    name: RELEASE
    runs-on: ubuntu-20.04
    steps:
      - name: clone repo
        uses: actions/checkout@v2.3.5
        with:
          repository: ${{ github.repository }}
          ref: develop
          fetch-depth: 1
      - name: create release branch
        run: |
          git checkout -b release/test-branch
          git tag v0.0.1
          git push --set-upstream origin release/test-branch
          git push origin v0.0.1
        shell: bash
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: Release v0.0.1
          draft: false
          prerelease: false
  # DEPLOY:
  #   name: DEPLOY
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Login Container Registry
  #       run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin<<<'${{ secrets.DOCKERHUB_TOKEN }}'
  #       shell: bash
  #     - name: clone repo
  #       uses: actions/checkout@v2.3.5
  #       with:
  #         repository: ${{ github.repository }}
  #         ref: ${{ github.ref }}
  #         fetch-depth: 1
  #     - name: Build Container Image
  #       run: docker build -t andromeda:latest . --compress
  #       shell: bash
  #     - name: Tag Container Image
  #       run: docker tag andromeda:latest dockerdemopai/andromeda:v0.0.1
  #       shell: bash
  #     - name: Push to Container Registry
  #       run: docker push dockerdemopai/andromeda:v0.0.1
  #       shell: bash