name: Deployment Workflow
on:
  push:
    branches:
      - develop
jobs:
  RELEASE:
    name: RELEASE
    runs-on: ubuntu-20.04
    steps:
      - name: create release branch
        run: |
          git checkout -b release/test-branch
          git push --set-upstream origin release/test-branch
        shell: bash
  # DEPLOY:
  #   name: DEPLOY
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Login Container Registry
  #       run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin<<<'${{ secrets.DOCKERHUB_TOKEN }}'
  #       shell: bash
  #     - name: clone repo
  #       uses: actions/checkout@v2.3.5
  #       with:
  #         repository: ${{ github.repository }}
  #         ref: ${{ github.ref }}
  #         fetch-depth: 1
  #     - name: Build Container Image
  #       run: docker build -t andromeda:latest . --compress
  #       shell: bash
  #     - name: Tag Container Image
  #       run: docker tag andromeda:latest dockerdemopai/andromeda:v0.0.1
  #       shell: bash
  #     - name: Push to Container Registry
  #       run: docker push dockerdemopai/andromeda:v0.0.1
  #       shell: bash