name: Deployment Workflow
on:
  push:
    branches:
      - feature/**
jobs:
  RELEASE:
    name: RELEASE
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2.3.5
        with:
          repository: ${{ github.repository }}
          ref: develop
          fetch-depth: 0
      - name: Get Latest Tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Create Release Branch
        run: |
          git checkout -b release/test-branch
          git push --set-upstream origin release/test-branch
        shell: bash
      - name: Get next Tag version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Generate Changelog
        id: generate_changelog
        uses: metcalfc/changelog-generator@v2.0.0
        with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          body: ${{steps.generate_changelog.outputs.changelog}}
          prerelease: false
          tag: ${{ steps.semvers.outputs.patch }}
          token: ${{ secrets.GITHUB_TOKEN }}
  # DEPLOY:
  #   name: DEPLOY
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Login Container Registry
  #       run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin<<<'${{ secrets.DOCKERHUB_TOKEN }}'
  #       shell: bash
  #     - name: clone repo
  #       uses: actions/checkout@v2.3.5
  #       with:
  #         repository: ${{ github.repository }}
  #         ref: ${{ github.ref }}
  #         fetch-depth: 1
  #     - name: Build Container Image
  #       run: docker build -t andromeda:latest . --compress
  #       shell: bash
  #     - name: Tag Container Image
  #       run: docker tag andromeda:latest dockerdemopai/andromeda:v0.0.1
  #       shell: bash
  #     - name: Push to Container Registry
  #       run: docker push dockerdemopai/andromeda:v0.0.1
  #       shell: bash